# Celo Chain Configuration

[chain]
chain_id = 42220
name = "Celo"
native_token = "CELO"
block_time_ms = 5000
explorer_url = "https://celoscan.io"

[chain.rpc]
# Environment variables can be referenced with ${VAR_NAME}
http = "${CELO_RPC_URL}"
ws = "${CELO_WS_URL}"
archive = "${CELO_ARCHIVE_URL}"
send = "${CELO_SEND_URL}"

[chain.gas]
# Celo uses EIP-1559
pricing = "Eip1559"
limit_multiplier = 1.3
max_gas_price_gwei = 50.0
priority_fee_gwei = 0.1
base_fee_buffer = 1.5

[chain.swap]
# Celo uses Uniswap V3
default_adapter = "uniswap_v3"

[chain.swap.uniswap_v3]
swap_router = "0x5615CDAb10dc425a742d643d949a7F474C01abc4"
quoter_v2 = "0x82825d0554fA07f7FC52Ab63c961F330fdEFa8E8"
factory = "0xAfE208a311B21f13EF87E33A90049fC17A7acDEc"
